export { default as git } from "./git.svg"
export { default as sun } from "./sun.svg"
export { default as moon } from "./moon.svg"
export {default as linkedin} from "./linkedin.svg"
export { default as yo } from "./FOTO.png"
export { default as trabajando } from "./trabajando.png"
export { default as trabajandooscuro } from "./trabajandooscuro.png"
export { default as book } from "./book.png"