export { default as git } from "./git.svg"
export { default as sun } from "./sun.svg"
export { default as moon } from "./moon.svg"
export {default as linkedin} from "./linkedin.svg"
export { default as yo } from "./FOTO.png"
export { default as trabajando } from "./trabajando.png"
export { default as trabajandooscuro } from "./trabajandooscuro.png"
export { default as book } from "./book.png"
export { default as letra } from "./letra.ttf"
export { default as descarga } from "./descarga.png"
export { default as info } from "./info.svg"
export { default as phone } from "./phone.svg"
export { default as house } from "./house.svg"
export { default as prueba } from "./prueba.png"


export { default as node } from "./node.svg"
export { default as  react} from "./react.png"
export { default as redux } from "./redux.svg"
export { default as html } from "./html.png"
export { default as css } from "./css.png"
export { default as js } from "./js.png"
export { default as ts } from "./ts.png"
export { default as tailwind } from "./tailwind.png"
export { default as sql } from "./sql.png"
export { default as photo } from "./photo.svg"
export { default as figma } from "./figma.svg"
export { default as bootstrap } from "./bootstrap.png"

export { default as gmail } from "./gmail.svg"
export { default as wtsp } from "./wtsp.svg"

export { default as twitter } from "./twitter.svg"
export { default as yourube } from "./youtube.svg"
export { default as discord } from "./discord.svg"
export { default as spotify } from "./spotify.svg"

export { default as pokemon } from "./pokemon.png"
export { default as molino } from "./molino.png"

export { default as google } from "./google.svg"